import { ArrowLeft, ChevronDown, Phone, AlertTriangle } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export function FAQPage() {
  const navigate = useNavigate();
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  useEffect(() => { window.scrollTo(0, 0); }, []);

  const sections = [
    { title: '1. Qui est mon contractant juridique ?', content: (<><p className="mb-3">Il est fondamental de distinguer deux types de relations contractuelles :</p><div className="space-y-3"><div className="bg-blue-50 rounded-xl p-4"><p className="font-semibold text-blue-900 mb-1">Pour le service numérique et la mise en relation</p><p className="text-sm">Votre contrat est conclu avec TROUVE TON DÉMÉNAGEUR (TTD). Notre responsabilité est limitée à la fourniture d&apos;outils technologiques, à l&apos;audit administratif des prestataires et à la gestion sécurisée de l&apos;intermédiation.</p></div><div className="bg-green-50 rounded-xl p-4"><p className="font-semibold text-green-900 mb-1">Pour l&apos;exécution matérielle du déménagement</p><p className="text-sm">Votre contrat de transport est conclu directement et exclusivement avec le Déménageur professionnel sélectionné. TTD n&apos;intervient jamais dans la chaîne de transport et n&apos;assume aucune des obligations légales liées à la qualité de transporteur ou de commissionnaire.</p></div></div></>) },
    { title: '2. Comment fonctionne le paiement sur la plateforme ?', content: (<><p className="mb-3">Lors de la réservation sur la plateforme TROUVE TON DÉMÉNAGEUR, le Client règle des frais de réservation correspondant à <strong>30 %</strong> du montant du devis affiché.</p><p className="mb-3">Ces frais rémunèrent le service de mise en relation, la réservation du créneau et l&apos;utilisation des outils numériques de la plateforme.</p><p className="mb-3">Le solde de la prestation (<strong>70 %</strong>) est réglé directement entre le Client et le Déménageur lors de l&apos;exécution du déménagement.</p><p className="text-sm text-gray-600">TROUVE TON DÉMÉNAGEUR n&apos;intervient pas dans ce paiement et n&apos;encaisse aucun montant au titre de la prestation de transport.</p></>) },
    { title: '4. Protocole d\'incident : que faire en cas de dommages ?', content: (<><p className="mb-3">En cas de dommage constaté, notre protocole de preuve par Intelligence Artificielle devient votre meilleur atout :</p><div className="space-y-3"><div className="bg-blue-50 rounded-lg p-3"><strong>Force Probante du Visuel :</strong> Si vous avez respecté le protocole (photos certifiées via l&apos;application avant le chargement), vous disposez d&apos;une base de preuve solide.</div><div className="bg-green-50 rounded-lg p-3"><strong>Rapport Technique d&apos;IA :</strong> TTD génère un rapport comparatif automatisé. Ce document technique est transmis à l&apos;assureur du déménageur pour accélérer l&apos;indemnisation.</div><div className="bg-purple-50 rounded-lg p-3"><strong>Action sur le Séquestre :</strong> En cas de litige déclaré, TTD peut assister les parties dans la transmission des éléments nécessaires à l&apos;ouverture d&apos;un dossier auprès de l&apos;assurance du Déménageur.</div></div></>) },
    { title: '5. Conditions et frais d\'annulation', content: (<><p className="mb-3">Le déménagement étant une prestation de transport à date déterminée, le droit de rétractation est exclu par la loi (Art. L. 221-28 12° du Code de la Consommation). Cependant, TTD propose un barème d&apos;annulation contractuel :</p><div className="space-y-2"><div className="flex items-start gap-2 bg-green-50 rounded-lg p-3 text-sm"><span className="text-green-600 font-bold mt-0.5 flex-shrink-0">✓</span><span><strong>J-10 ou plus :</strong> Remboursement intégral des frais de réservation (hors frais techniques Stripe).</span></div><div className="flex items-start gap-2 bg-yellow-50 rounded-lg p-3 text-sm"><span className="text-yellow-600 font-bold mt-0.5 flex-shrink-0">!</span><span><strong>Entre J-9 et J-5 :</strong> Remboursement de 50 % des frais de réservation.</span></div><div className="flex items-start gap-2 bg-red-50 rounded-lg p-3 text-sm"><span className="text-red-600 font-bold mt-0.5 flex-shrink-0">✗</span><span><strong>Moins de 5 jours avant la mission :</strong> Les frais de réservation sont intégralement conservés à titre d&apos;indemnité contractuelle.</span></div></div></>) },
    { title: '6. Litige sur le volume ou l\'accès le jour J', content: (<p>Le Déménageur peut exercer un droit de retrait ou exiger un complément tarifaire si la réalité du terrain diffère manifestement de votre déclaration (ex : volume réel de 30m³ au lieu de 15m³, étages non déclarés). Dans cette hypothèse, TTD pourra assister les parties dans leurs échanges afin de faciliter une résolution amiable du litige sur la base des éléments fournis par le Client et le Déménageur.</p>) },
    { title: '7. Sécurité des données et des flux financiers', content: (<div className="space-y-3"><div className="bg-gray-50 rounded-lg p-3"><strong>Stripe :</strong> Vos données bancaires sont traitées par Stripe (standard PCI-DSS), TTD n&apos;y a jamais accès.</div><div className="bg-gray-50 rounded-lg p-3"><strong>Vercel :</strong> Votre patrimoine numérique (photos de vos biens) est hébergé sur des serveurs sécurisés bénéficiant des plus hauts standards de cryptage.</div><div className="bg-gray-50 rounded-lg p-3"><strong>RGPD :</strong> Conformément à notre politique de confidentialité, vos coordonnées ne sont transmises au prestataire qu&apos;après validation effective de la réservation pour prévenir toute sollicitation non sollicitée.</div></div>) },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="max-w-5xl mx-auto px-4 py-8">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-blue-600 hover:text-blue-800 mb-6 group"><ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" /><span className="font-medium">Retour</span></button>
        <main>
          <div className="text-center mb-8"><h1 className="text-4xl font-extrabold text-gray-900 mb-3">FAQ Juridique et Assistance</h1><p className="text-lg text-gray-500">TROUVE TON DÉMÉNAGEUR</p></div>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-8 flex items-start gap-3"><AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" /><p className="text-sm text-amber-800"><strong>Avertissement juridique :</strong> Cette foire aux questions (FAQ) est mise à disposition à titre purement informatif et pédagogique pour faciliter la compréhension du fonctionnement de la plateforme. Elle ne possède aucune valeur contractuelle et ne se substitue en aucun cas aux Conditions Générales d&apos;Utilisation et de Vente (CGU/CGV) qui constituent la seule base légale de votre relation avec TROUVE TON DÉMÉNAGEUR (TTD).</p></div>
          <div className="space-y-3">
            {sections.map((section, index) => { const isOpen = openIndex === index; return (<div key={index} className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden"><button onClick={() => setOpenIndex(isOpen ? null : index)} className="w-full px-8 py-6 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"><span className="text-lg font-semibold text-gray-900 pr-4">{section.title}</span><ChevronDown className={`w-6 h-6 text-gray-400 flex-shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`} /></button>{isOpen && <div className="px-8 pb-6 text-gray-700 leading-relaxed">{section.content}</div>}</div>); })}
          </div>
          <div className="mt-16 bg-gradient-to-br from-blue-900 to-slate-900 rounded-3xl p-12 text-white text-center"><h2 className="text-3xl font-bold mb-4">Besoin d&apos;aide ?</h2><p className="text-xl text-blue-100 mb-8">Notre équipe support est là pour vous aider</p><div className="flex flex-col sm:flex-row gap-4 justify-center items-center"><a href="mailto:support@trouvetondemenageur.fr" className="bg-white text-blue-600 px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-50 transition-all duration-300 transform hover:scale-105">support@trouvetondemenageur.fr</a><a href="tel:0189707881" className="flex items-center gap-3 bg-blue-700 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-600 transition-all duration-300 transform hover:scale-105 border border-blue-500"><Phone className="w-5 h-5" />01 89 70 78 81</a></div></div>
        </main>
      </div>
    </div>
  );
}
