import { ArrowLeft, ChevronDown, Phone } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

export default function PrivacyPolicyPage() {
  const navigate = useNavigate();
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  useEffect(() => { window.scrollTo(0, 0); }, []);

  const sections = [
    { title: '1. Responsable du traitement', content: (<p>Le responsable du traitement des données est la société TROUVE TON DÉMÉNAGEUR, Société par Actions Simplifiée à Associé Unique (SASU) au capital de 1 000 €, immatriculée au RCS de Paris sous le n° 101 378 248, dont le siège social est situé au 60 rue François 1er, 75008 Paris.</p>) },
    { title: '2. Données collectées', content: (<><p className="mb-3">Nous collectons uniquement les données nécessaires à la fourniture de nos services d&apos;intermédiation :</p><div className="bg-gray-50 rounded-xl p-4 space-y-2"><p><strong>Identité :</strong> Nom, prénom.</p><p><strong>Contact :</strong> Adresse e-mail, numéro de téléphone.</p><p><strong>Mission :</strong> Adresses de chargement et de livraison, inventaire des biens.</p><p><strong>Patrimoine numérique :</strong> Clichés photographiques de vos biens capturés via notre interface pour le protocole de preuve par IA.</p><p><strong>Données de paiement :</strong> Les transactions sont gérées par Stripe (TTD n&apos;a pas accès à vos numéros de carte bancaire).</p></div><p className="mt-3 text-sm text-gray-600">Les clichés transmis via la plateforme ne doivent pas contenir de données sensibles au sens de l&apos;article 9 du RGPD (documents d&apos;identité, données de santé, informations financières visibles). L&apos;Utilisateur demeure responsable du contenu des éléments transmis.</p></>) },
    { title: '3. Finalités et bases légales', content: (<><p className="mb-3">Le traitement de vos données repose sur les bases suivantes :</p><div className="space-y-2"><div className="bg-blue-50 rounded-lg p-3"><strong>Exécution du contrat :</strong> Mise en relation avec le déménageur, gestion de la réservation et gestion des frais de mise en relation.</div><div className="bg-green-50 rounded-lg p-3"><strong>Intérêt légitime :</strong> Constitution d&apos;un protocole de preuve numérique par Intelligence Artificielle pour sécuriser l&apos;exécution de la prestation.</div><div className="bg-purple-50 rounded-lg p-3"><strong>Obligation légale :</strong> Vigilance administrative (KYB) et lutte contre la fraude.</div></div><p className="mt-3 text-sm text-gray-600">TTD ne vend, ne loue ni ne cède les données personnelles des utilisateurs à des tiers à des fins commerciales.</p></>) },
    { title: '4. Utilisation de l\'Intelligence Artificielle', content: (<p>Les outils d&apos;intelligence artificielle utilisés par TTD interviennent exclusivement comme outils d&apos;assistance technique à l&apos;analyse des données. Aucun traitement automatisé produisant des effets juridiques au sens de l&apos;article 22 du RGPD n&apos;est mis en œuvre sans intervention humaine. Toute décision relative à un blocage de fonds, un signalement ou un arbitrage est validée par un membre habilité de l&apos;équipe TTD.</p>) },
    { title: '5. Destinataires des données et transferts hors UE', content: (<><p className="mb-3">Vos données sont transmises :</p><ul className="space-y-2 ml-4 list-none mb-3"><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">1.</span><span><strong>Au Déménageur sélectionné :</strong> uniquement après validation de la réservation.</span></li><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">2.</span><span><strong>À nos prestataires techniques :</strong> Stripe (paiement), Vercel (hébergement), OpenAI (assistance technique).</span></li></ul><p className="text-sm text-gray-600">Ces prestataires agissent en qualité de sous-traitants au sens de l&apos;article 28 du RGPD et sont contractuellement tenus d&apos;assurer la confidentialité et la sécurité des données traitées pour le compte de TTD. Certains prestataires (Stripe, OpenAI) peuvent impliquer des transferts de données hors de l&apos;Union Européenne. Ces transferts sont rigoureusement encadrés par les clauses contractuelles types (CCT) de la Commission Européenne afin de garantir un niveau de protection équivalent au RGPD.</p></>) },
    { title: '6. Durée de conservation', content: (<div className="space-y-2"><div className="bg-gray-50 rounded-lg p-3"><strong>Données clients :</strong> Conservées pendant la durée de la relation contractuelle, augmentée des délais de prescription légale (5 ans).</div><div className="bg-gray-50 rounded-lg p-3"><strong>Photos du protocole IA :</strong> Conservées jusqu&apos;à 6 mois après la fin de la mission, sauf en cas de litige déclaré où elles sont conservées jusqu&apos;à la résolution complète du dossier.</div><div className="bg-gray-50 rounded-lg p-3"><strong>Données de facturation et de transaction :</strong> conservées pendant la durée légale de conservation comptable applicable (10 ans).</div></div>) },
    { title: '7. Vos droits', content: (<><p className="mb-3">Conformément aux articles 15 à 22 du RGPD, vous disposez :</p><ul className="space-y-1 ml-4 list-none mb-3"><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">•</span>d&apos;un droit d&apos;accès</li><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">•</span>d&apos;un droit de rectification</li><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">•</span>d&apos;un droit d&apos;effacement</li><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">•</span>d&apos;un droit à la limitation du traitement</li><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">•</span>d&apos;un droit d&apos;opposition</li><li className="flex items-start gap-2"><span className="text-blue-600 mt-1">•</span>d&apos;un droit à la portabilité des données</li></ul><p className="mb-3">Vous pouvez exercer ces droits à tout moment en écrivant à <a href="mailto:support@trouvetondemenageur.fr" className="text-blue-600 hover:underline">support@trouvetondemenageur.fr</a>. En cas de difficulté non résolue, vous disposez du droit d&apos;introduire une réclamation auprès de la CNIL (<a href="https://www.cnil.fr" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">www.cnil.fr</a>).</p><p className="text-sm text-gray-600">TTD n&apos;est pas tenue de désigner un Délégué à la Protection des Données au regard de la nature et du volume des traitements réalisés. Toute question relative à la protection des données peut être adressée à : support@trouvetondemenageur.fr.</p></>) },
    { title: '8. Sécurité des données', content: (<><p className="mb-3">TTD met en œuvre des mesures techniques et organisationnelles appropriées afin de garantir un niveau de sécurité adapté au risque, notamment chiffrement des données, contrôle des accès, journalisation des connexions et hébergement sur serveurs sécurisés.</p><p className="text-sm text-gray-600">Les cookies non essentiels sont déposés uniquement après consentement de l&apos;utilisateur conformément à l&apos;article 82 de la loi Informatique et Libertés. Pour plus d&apos;informations sur l&apos;utilisation des cookies et traceurs, veuillez consulter la Politique relative aux Cookies accessible sur le site.</p></>) },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="max-w-5xl mx-auto px-4 py-8">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-blue-600 hover:text-blue-800 mb-6 group"><ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" /><span className="font-medium">Retour</span></button>
        <main>
          <div className="text-center mb-12"><h1 className="text-4xl font-extrabold text-gray-900 mb-3">Politique de Confidentialité</h1><p className="text-lg text-gray-500">www.trouvetondemenageur.fr</p></div>
          <p className="mb-8 text-gray-600 text-center max-w-3xl mx-auto">La présente Politique de confidentialité définit la manière dont la société TROUVE TON DÉMÉNAGEUR, Société par Actions Simplifiée à Associé Unique (SASU) collecte, traite et protège les données à caractère personnel des utilisateurs de la plateforme accessible à l&apos;adresse www.trouvetondemenageur.fr.</p>
          <div className="space-y-3">
            {sections.map((section, index) => { const isOpen = openIndex === index; return (<div key={index} className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden"><button onClick={() => setOpenIndex(isOpen ? null : index)} className="w-full px-8 py-6 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"><span className="text-lg font-semibold text-gray-900 pr-4">{section.title}</span><ChevronDown className={`w-6 h-6 text-gray-400 flex-shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`} /></button>{isOpen && <div className="px-8 pb-6 text-gray-700 leading-relaxed">{section.content}</div>}</div>); })}
          </div>
          <div className="mt-16 bg-gradient-to-br from-blue-900 to-slate-900 rounded-3xl p-12 text-white text-center"><h2 className="text-3xl font-bold mb-4">Une question sur vos données ?</h2><p className="text-xl text-blue-100 mb-8">Notre équipe support est là pour vous aider</p><div className="flex flex-col sm:flex-row gap-4 justify-center items-center"><a href="mailto:support@trouvetondemenageur.fr" className="bg-white text-blue-600 px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-50 transition-all duration-300 transform hover:scale-105">support@trouvetondemenageur.fr</a><a href="tel:0189707881" className="flex items-center gap-3 bg-blue-700 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-600 transition-all duration-300 transform hover:scale-105 border border-blue-500"><Phone className="w-5 h-5" />01 89 70 78 81</a></div></div>
        </main>
      </div>
    </div>
  );
}
